<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseparalelo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paralelo');
        $this->hasColumn('CodigoParalelo', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Paralelo', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));


        $this->index('CursoParaleloPeriodoIndex', array(
             'fields' => 
             array(
              'Paralelo' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('cursoalumno as relparalelo', array(
             'local' => 'CodigoParalelo',
             'foreign' => 'CodigoParalelo'));
    }
}