<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseperiodoescolar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periodoescolar');
        $this->hasColumn('CodigoPeriodoEscolar', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoPeriodo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('PeriodoEscolar', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('FechaInicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('FechaFin', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));


        $this->index('PeriodoIndex', array(
             'fields' => 
             array(
              'CodigoPeriodo' => 
              array(
              ),
              'PeriodoEscolar' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('periodo as relperiodo', array(
             'local' => 'CodigoPeriodo',
             'foreign' => 'CodigoPeriodo'));

        $this->hasMany('parcial as relperiodoescolar', array(
             'local' => 'CodigoPeriodoEscolar',
             'foreign' => 'CodigoPeriodoEscolar'));
    }
}