<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso');
        $this->hasColumn('CodigoCurso', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Curso', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));


        $this->index('CursoParaleloPeriodoIndex', array(
             'fields' => 
             array(
              'Curso' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('cursoalumno as relcurso', array(
             'local' => 'CodigoCurso',
             'foreign' => 'CodigoCurso'));
    }
}