<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basenovedad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('novedad');
        $this->hasColumn('CodigoNovedad', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoAlumno', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoInspector', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoParcial', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Fugas', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Atrasos', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Indisciplinas', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));

        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('alumno as relalumno', array(
             'local' => 'CodigoAlumno',
             'foreign' => 'CodigoAlumno'));

        $this->hasOne('inspector as relinspector', array(
             'local' => 'CodigoInspector',
             'foreign' => 'CodigoInspector'));

        $this->hasOne('parcial as relparcial', array(
             'local' => 'CodigoParcial',
             'foreign' => 'CodigoParcial'));

        $this->hasMany('novedadcursomateriahorario as relnovedad', array(
             'local' => 'CodigoNovedad',
             'foreign' => 'CodigoNovedad'));
    }
}