<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseperiodo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periodo');
        $this->hasColumn('CodigoPeriodo', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Periodo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));


        $this->index('PeriodoIndex', array(
             'fields' => 
             array(
              'Periodo' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('periodoescolar as relperiodo', array(
             'local' => 'CodigoPeriodo',
             'foreign' => 'CodigoPeriodo'));
    }
}