<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basecursoalumno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cursoalumno');
        $this->hasColumn('CodigoCursoAlumno', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoAlumno', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoPeriodo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoCurso', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoParalelo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('CursoAlumnoIndex', array(
             'fields' => 
             array(
              'CodigoAlumno' => 
              array(
              ),
              'CodigoPeriodo' => 
              array(
              ),
              'CodigoCurso' => 
              array(
              ),
              'CodigoParalelo' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('periodo as relperiodo', array(
             'local' => 'CodigoPeriodo',
             'foreign' => 'CodigoPeriodo'));

        $this->hasOne('curso as relcurso', array(
             'local' => 'CodigoCurso',
             'foreign' => 'CodigoCurso'));

        $this->hasOne('paralelo as relparalelo', array(
             'local' => 'CodigoParalelo',
             'foreign' => 'CodigoParalelo'));

        $this->hasOne('alumno as relalumno', array(
             'local' => 'CodigoAlumno',
             'foreign' => 'CodigoAlumno'));
    }
}