<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basenovedadcursomateriahorario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('novedadcursomateriahorario');
        $this->hasColumn('CodigoNovedadCursoMateriaHorario', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoNovedad', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoCursoMateriaHorario', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoTipoNovedad', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('CursoNovedadMateriaHorarioIndex', array(
             'fields' => 
             array(
              'CodigoNovedad' => 
              array(
              ),
              'CodigoCursoMateriaHorario' => 
              array(
              ),
              'CodigoTipoNovedad' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('novedad as relnovedad', array(
             'local' => 'CodigoNovedad',
             'foreign' => 'CodigoNovedad'));

        $this->hasOne('cursomateriahorario as relcursomateriahorario', array(
             'local' => 'CodigoCursoMateriaHorario',
             'foreign' => 'CodigoCursoMateriaHorario'));

        $this->hasOne('tiponovedad as reltiponovedad', array(
             'local' => 'CodigoTipoNovedad',
             'foreign' => 'CodigoTipoNovedad'));
    }
}