<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseinspector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inspector');
        $this->hasColumn('CodigoInspector', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Cedula', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('Nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('Apellido', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('Telefono', 'string', 12, array(
             'type' => 'string',
             'length' => '12',
             ));
        $this->hasColumn('Celular', 'string', 13, array(
             'type' => 'string',
             'length' => '13',
             ));
        $this->hasColumn('CorreoElectronico', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('Imagen', 'blob', null, array(
             'type' => 'blob',
             ));


        $this->index('CedulaIndex', array(
             'fields' => 
             array(
              'Cedula' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('novedad as relinspector', array(
             'local' => 'CodigoInspector',
             'foreign' => 'CodigoInspector'));
    }
}