<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseparametro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametro');
        $this->hasColumn('CodigoParametro', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Parametro', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('TipoParametro', 'char', 1, array(
             'type' => 'char',
             'notnull' => true,
             'length' => '1',
             ));
        $this->hasColumn('ValorInt', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('ValorString', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('Imagen', 'blob', null, array(
             'type' => 'blob',
             ));


        $this->index('ParametroIndex', array(
             'fields' => 
             array(
              'Parametro' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

}