<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basetiponovedad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tiponovedad');
        $this->hasColumn('CodigoTipoNovedad', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Novedad', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));


        $this->index('NovedadIndex', array(
             'fields' => 
             array(
              'Novedad' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('novedadcursomateriahorario as reltiponovedad', array(
             'local' => 'CodigoTipoNovedad',
             'foreign' => 'CodigoTipoNovedad'));
    }
}