<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseparcial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parcial');
        $this->hasColumn('CodigoParcial', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoPeriodoEscolar', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Parcial', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));


        $this->index('PeriodoIndex', array(
             'fields' => 
             array(
              'CodigoPeriodoEscolar' => 
              array(
              ),
              'Parcial' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('periodoescolar as relperiodoescolar', array(
             'local' => 'CodigoPeriodoEscolar',
             'foreign' => 'CodigoPeriodoEscolar'));

        $this->hasMany('novedad as relparcial', array(
             'local' => 'CodigoParcial',
             'foreign' => 'CodigoParcial'));
    }
}