<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basecursomateriahorario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cursomateriahorario');
        $this->hasColumn('CodigoCursoMateriaHorario', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoPeriodo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoCurso', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoParalelo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoHorario', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoDia', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoMateria', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));


        $this->index('CursoMateriaHorarioIndex', array(
             'fields' => 
             array(
              'CodigoPeriodo' => 
              array(
              ),
              'CodigoCurso' => 
              array(
              ),
              'CodigoParalelo' => 
              array(
              ),
              'CodigoHorario' => 
              array(
              ),
              'CodigoDia' => 
              array(
              ),
              'CodigoMateria' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('periodo as relperiodo', array(
             'local' => 'CodigoPeriodo',
             'foreign' => 'CodigoPeriodo'));

        $this->hasOne('curso as relcurso', array(
             'local' => 'CodigoCurso',
             'foreign' => 'CodigoCurso'));

        $this->hasOne('paralelo as relparalelo', array(
             'local' => 'CodigoParalelo',
             'foreign' => 'CodigoParalelo'));

        $this->hasOne('materia as relmateria', array(
             'local' => 'CodigoMateria',
             'foreign' => 'CodigoMateria'));

        $this->hasOne('dia as reldia', array(
             'local' => 'CodigoDia',
             'foreign' => 'CodigoDia'));

        $this->hasOne('horario as relhorario', array(
             'local' => 'CodigoHorario',
             'foreign' => 'CodigoHorario'));

        $this->hasMany('novedadcursomateriahorario as relcursomateriahorario', array(
             'local' => 'CodigoCursoMateriaHorario',
             'foreign' => 'CodigoCursoMateriaHorario'));
    }
}