<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basedia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dia');
        $this->hasColumn('CodigoDia', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Dia', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('Horas', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));


        $this->index('DiaIndex', array(
             'fields' => 
             array(
              'Dia' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('cursomateriahorario as reldia', array(
             'local' => 'CodigoDia',
             'foreign' => 'CodigoDia'));
    }
}