<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basenovedadalumnoparcial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('novedadalumnoparcial');
        $this->hasColumn('CodigoNovedadCursoMateriaHorario', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('CodigoAlumno', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('CodigoParcial', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('Fecha', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Apellido', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('Nombre', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('Novedad', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('Curso', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('Paralelo', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('Materia', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('Horario', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

}