<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basemateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materia');
        $this->hasColumn('CodigoMateria', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('Materia', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('Descripcion', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('Imagen', 'blob', null, array(
             'type' => 'blob',
             ));


        $this->index('MateriaIndex', array(
             'fields' => 
             array(
              'Materia' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'latin1');
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('cursomateriahorario as relmateria', array(
             'local' => 'CodigoMateria',
             'foreign' => 'CodigoMateria'));
    }
}