<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/22 04:22:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cnpbasedatosinspeccion',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
