<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/22 04:22:44
sfConfig::add(array(
  'app_max_resultados_por_pagina' => 7,
  'app_max_edad_alumno' => 20,
  'app_max_rango_anios' => 5,
  'app_sf_guard_plugin_success_signin_url' => '/',
  'app_sf_guard_plugin_success_signout_url' => '/',
));
