<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/22 04:22:44
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
