<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cursoTable extends Doctrine_Table
{
	public function getActiveCursosQuery()
	{
	  $q = Doctrine_Query::create()->from('curso c')->orderBy('c.codigoperiodo,c.codigocurso');	 
	  return $q->execute();
	}
}