<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class curso extends Basecurso
{
	public function __toString()
	{	
		return $this->getCurso();
	}
	public function getActiveCursosQuery()
	{
	  $q = Doctrine_Query::create()->from('curso c')->orderBy('c.curso asc');	 
	  return $q;
	}
	public function getActiveCursos($max = 10)
	{
	  $q = $this->getActiveCursos()->limit($max);	 
	  return $q->execute();
	}
	 
	public function countActiveCursos()
	{
	  return $this->getActiveCursosQuery()->count();
	}	
}