<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class dia extends Basedia
{
	public function __toString()
	{
		return sprintf('%s', $this->getDia());
	}
	
	public function getActiveDiasQuery()
	{
	  $q = Doctrine_Query::create()->from('dia d')->orderBy('d.codigodia');	 
	  return $q;
	}
	public function getActiveDias($max = 10)
	{
	  $q = $this->getActiveDiasQuery()->limit($max);	 
	  return $q->execute();
	}
	 
	public function countActiveDias()
	{
	  return $this->getActiveDiasQuery()->count();
	}	
}