<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class falta extends Basefalta
{
	public function getActiveFaltasQuery()
	{
	  $q = Doctrine_Query::create()->from('falta f')->orderBy('f.codigoalumno,f.fecha desc');	 
	  return $q;
	}
	public function getActiveFaltas($max = 10)
	{
	  $q = $this->getActiveFaltas()->limit($max);	 
	  return $q->execute();
	}
	 
	public function countActiveFaltas()
	{
	  return $this->getActiveFaltasQuery()->count();
	}
	
	public function getNombreCompletoAlumno($codigoAlumno)
	{
		$arregloAlumno = Doctrine::getTable('alumno')
		->createQuery('a')
		->select('a.*')			   
		->where('a.codigoalumno = ?', $codigoAlumno)		   			   
		->execute();
		$alumno = $arregloAlumno->getFirst();
		return sprintf('%s %s',$alumno->getApellido(),$alumno->getNombre());
	}
	public function getNombreCompletoInspector($codigoInspector)
	{
		$arregloInspector = Doctrine::getTable('inspector')
		->createQuery('i')
		->select('i.*')			   
		->where('i.codigoinspector = ?', $codigoInspector)		   			   
		->execute();
		$inspector = $arregloInspector->getFirst();
		return sprintf('%s %s',$inspector->getApellido(),$inspector->getNombre());
	}
	public function getTipoFalta($codigoTipoFalta)
	{
		$arregloTipoFalta = Doctrine::getTable('tipofalta')
		->createQuery('tf')
		->select('tf.*')			   
		->where('tf.codigotipofalta = ?', $codigoTipoFalta)		   			   
		->execute();
		$tipofalta = $arregloTipoFalta->getFirst();
		return $tipofalta->getFalta();
	}
	public function getParcial($codigoParcial)
	{
		$arregloParcial = Doctrine::getTable('parcial')
		->createQuery('p')
		->select('p.*')			   
		->where('p.codigoparcial = ?', $codigoParcial)		   			   
		->execute();
		$parcial = $arregloParcial->getFirst();
		return $parcial;
	}
}