<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class inspector extends Baseinspector
{
	public function __toString()
	{	
		return sprintf('%s %s - CI: %s ', $this->getApellido(), $this->getNombre(),$this->getCedula());
	}
	
	public function getActiveInspectoresQuery()
	{
	  $q = Doctrine_Query::create()->from('inspector i')->orderBy('i.apellido,i.nombre');	 
	  return $q;
	}
	
	public function getActiveInspectores($max = 10)
	{
	  $q = $this->getActiveInspectoresQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActiveInspectores()
	{
	  return $this->getActiveInspectoresQuery()->count();
	}
}