<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class materia extends Basemateria
{
	public function __toString()
	{
		return sprintf('%s', $this->getMateria());
	}
	
	public function getActiveMateriasQuery()
	{
	  $q = Doctrine_Query::create()->from('materia m')->orderBy('m.materia');	 
	  return $q;
	}
	
	public function getActiveMaterias($max = 10)
	{
	  $q = $this->getActiveMateriasQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActiveMaterias()
	{
	  return $this->getActiveMateriasQuery()->count();
	}
}