<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class novedadcursomateriahorario extends Basenovedadcursomateriahorario
{
	public function registrarNovedad($codigoNovedad,$codigoCurso,$codigoHorario,$codigoDia,$tipoNovedad)
	{		 
		$coleccionTipoNovedad = Doctrine::getTable('tiponovedad')
		->createQuery('n')
		->where('n.novedad like ? ',$tipoNovedad."%") 
		->execute(); 
		if (empty($coleccionTipoNovedad[0]['CodigoTipoNovedad']))
		{
			return false;
		}
		$coleccionCursoMateriaHorario = Doctrine::getTable('cursomateriahorario')
		->createQuery('c')
		->where('c.codigocurso = ? and c.codigohorario = ? and c.codigodia = ? ',array($codigoCurso,$codigoHorario,$codigoDia)) 
		->execute(); 
		if (empty($coleccionCursoMateriaHorario[0]['CodigoCursoMateriaHorario']))
		{
			return false;
		}	
		$novedadcursomateriahorario = new novedadcursomateriahorario();
		$novedadcursomateriahorario->setCodigoNovedad($codigoNovedad);
		$novedadcursomateriahorario->setCodigoCursoMateriaHorario($coleccionCursoMateriaHorario[0]['CodigoCursoMateriaHorario']);	
		$novedadcursomateriahorario->setCodigoTipoNovedad($coleccionTipoNovedad[0]['CodigoTipoNovedad']);	
		$novedadcursomateriahorario->save();
		return true;
	}
	public function borrarPorCodigoNovedad($codigoNovedad)
	{
		$queryBorrarNovedadPorCodigo = Doctrine_Query::create()
        ->delete('novedadcursomateriahorario ncmh')        
        ->where('ncmh.codigonovedad = ?',array($codigoNovedad))
		->execute();
	}
}