<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class novedad extends Basenovedad
{
	public function getActiveNovedadesQuery()
	{
	  $q = Doctrine_Query::create()->from('novedad n')->orderBy('n.fecha desc,n.codigoalumno');	 
	  return $q;
	}
	
	public function getActiveNovedades($max = 10)
	{
	  $q = $this->getActiveNovedadesQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActiveNovedades()
	{
	  return $this->getActiveNovedadesQuery()->count();
	}
	public function getNombreCompletoAlumno($codigoAlumno)
	{
		$arregloAlumno = Doctrine::getTable('alumno')
		->createQuery('a')
		->select('a.*')			   
		->where('a.codigoAlumno = ?', $codigoAlumno)		   			   
		->execute();
		$alumno = $arregloAlumno->getFirst();
		return sprintf('%s %s',$alumno->getApellido(),$alumno->getNombre());
	}
	public function getCedulaAlumno($codigoAlumno)
	{
		$arregloAlumno = Doctrine::getTable('alumno')
		->createQuery('a')
		->select('a.*')			   
		->where('a.codigoAlumno = ?', $codigoAlumno)		   			   
		->execute();
		$alumno = $arregloAlumno->getFirst();
		return sprintf('%s',$alumno->getCedula());
	}
	
	public function getNombreCompletoInspector($codigoInspector)
	{
		$arregloInspector = Doctrine::getTable('inspector')
		->createQuery('i')
		->select('i.*')			   
		->where('i.codigoinspector = ?', $codigoInspector)		   			   
		->execute();
		$inspector = $arregloInspector->getFirst();
		return sprintf('%s %s',$inspector->getApellido(),$inspector->getNombre());
	}
	
	public function getParcial($codigoParcial)
	{
		$arregloParcial = Doctrine::getTable('parcial')
		->createQuery('p')
		->select('p.*')			   
		->where('p.codigoparcial = ?', $codigoParcial)		   			   
		->execute();
		$parcial = $arregloParcial->getFirst();
		return $parcial;
	}

}