<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class parcial extends Baseparcial
{
	public function __toString()
	{	
		$periodoescolar = Doctrine::getTable('periodoescolar')
		->createQuery('pe')
		->where('pe.codigoperiodoescolar = ? ',$this->getCodigoPeriodoEscolar()) 
		->execute(); 		
		$periodo = Doctrine::getTable('periodo')
		->createQuery('p')
		->where('p.codigoPeriodo = ? ',$periodoescolar[0]['CodigoPeriodo']) 
		->execute(); 
		return sprintf('%s - %s - %s', $this->getParcial(), $periodoescolar[0]['PeriodoEscolar'],$periodo[0]['Periodo']);
	}
	
	public function getActiveParcialesQuery()
	{
	  $q = Doctrine_Query::create()->from('parcial p')->orderBy('p.codigoperiodoescolar,p.parcial');	 
	  return $q;
	}
	
	public function getActiveParciales($max = 10)
	{
	  $q = $this->getActiveParcialesQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActiveParciales()
	{
	  return $this->getActiveParcialesQuery()->count();
	}
	public function getPeriodoEscolar($codigoPeriodoEscolar)
	{
		$arregloPeriodoEscolar = Doctrine::getTable('periodoescolar')
		->createQuery('pe')
		->select('pe.*')			   
		->where('pe.codigoperiodoescolar = ?', $codigoPeriodoEscolar)		   			   
		->execute();
		$periodoescolar = $arregloPeriodoEscolar->getFirst();
		return $periodoescolar;
	}
}