<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class periodo extends Baseperiodo
{
	public function __toString()
	{
		return sprintf('%s', $this->getPeriodo());
	}
	public function getActivePeriodosQuery()
	{
	  $q = Doctrine_Query::create()->from('periodo p')->orderBy('p.periodo asc');	 
	  return $q;
	}
	
	public function getActivePeriodos($max = 10)
	{
	  $q = $this->getActivePeriodosQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActivePeriodos()
	{
	  return $this->getActivePeriodosQuery()->count();
	}
}