<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tipofalta extends Basetipofalta
{
	public function __toString()
	{	
		return sprintf('%s ', $this->getFalta());
	}
	
	public function getActiveFaltasQuery()
	{
	  $q = Doctrine_Query::create()->from('tipofalta tf')->orderBy('tf.falta asc');	 
	  return $q;
	}
	
	public function getActiveFaltas($max = 10)
	{
	  $q = $this->getActiveFaltasQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActiveFaltas()
	{
	  return $this->getActiveFaltasQuery()->count();
	}
}