<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tiponovedad extends Basetiponovedad
{
	public function getActiveNovedadesQuery()
	{
	  $q = Doctrine_Query::create()->from('tiponovedad tn')->orderBy('tn.novedad asc');	 
	  return $q;
	}
	
	public function getActiveNovedades($max = 10)
	{
	  $q = $this->getActiveNovedadesQuery()->limit($max);	 
	  return $q->execute();
	}
	
	public function countActiveNovedades()
	{
	  return $this->getActiveNovedadesQuery()->count();
	}

}