default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,bootstrap.css,offcanvas.css,bootstrap-combobox.css]

  javascripts:    [jquery-1.10.2.min.js,bootstrap.js,bootstrap-combobox.js,offcanvas.js,enumareaciones.js,jquery.inputmask.js,jquery.inputmask.regex.extensions.js,aplicacion.mascara.js,error.mensaje.alerta.js,jquery.core.widgets.js,animaciones.js,periodosFiscales.js]

  has_layout:     on
  layout:         layout
