<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/05/22 03:56:04
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrar',
        1 => 'registrar',
        2 => 'reporte',
      ),
    ),
  ),
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrar',
        1 => 'registrar',
        2 => 'reporte',
      ),
    ),
  ),
);
